---

- name: install cifs required packages
  package:
    name: "{{ smb_packages }}"
    state: present
  when:
    - mount_fstypes | regex_search("cifs")

- name: install nfs required packages
  package:
    name: "{{ nfs_packages }}"
    state: present
  when:
    - mount_fstypes | regex_search("nfs*")

...
